Introduce SignatureShare aggregator for AT2 transfers
maidsafe/sn_client pull request #1271
Opened 2020-10-08 11:05 UTC by Yoga07

2020-10-09 06:43 UTC, joshuef requested changes

2020-10-09 06:43 UTC, joshuef commented on src/client/transfer_actor/balance_management.rs
> +            .send_money(PublicKey::Bls(random_pk), Money::from_str("0")?)
@Yoga07 this should fail no?

2020-10-09 06:43 UTC, joshuef commented on src/client/transfer_actor/balance_management.rs
> +        // Try transferring money exceeding our balance.
@Yoga07 this should be another test IMO. `cannot_transfer_in_excess_of_funds`

2020-10-09 06:43 UTC, joshuef commented on src/connection_manager.rs
> +struct DebitProofAggregator {
I'm not sure this should be handled a) in connection_manager, or b) in the client... Isn't this already handled by transfers? Or if not.. .should it be handled there?

2020-10-09 06:43 UTC, joshuef commented on src/connection_manager.rs
> +            if self.elders.len() >= 7 {
We may not be able to connect to all 7... do we need all 7? 

This is an ongoing thing we need to look at... what is acceptable for us here?

2020-10-09 06:43 UTC, joshuef commented on src/connection_manager.rs
> +                                if let Event::TransferValidated { event, .. } = event {
Again, I'm not sure this is necessary vs just passing in to the actor. That should spit out a debitProof when there's enough sigs

2020-10-15 07:08 UTC, Yoga07 commented on src/connection_manager.rs
> +            if self.elders.len() >= 7 {
Section spin-up has become a lot more reliable with the latest routing changes and we are now consistently having 7 Elders starting good. So it would be ideal for the client to start connecting to 7 nodes I believe :)

2020-10-15 13:58 UTC, Yoga07 commented on src/client/transfer_actor/balance_management.rs
> +        // Try transferring money exceeding our balance.
Will push in the upcoming PR :+1:

2020-10-15 14:14 UTC, lionel1704 submitted a review, later dismissed

2020-10-15 14:16 UTC, Yoga07 commented on src/client/transfer_actor/balance_management.rs
> +            .send_money(PublicKey::Bls(random_pk), Money::from_str("0")?)
We've been allowing zero-value transfers so far, but with that fixed in maidsafe/sn_transfers#41, changes have been made to reflect the same :+1:

2020-10-22 07:47 UTC, lionel1704 approved these changes
Just a trivial comment!

2020-10-22 07:47 UTC, lionel1704 commented on src/connection_manager.rs
> +            if self.elders.len() >= 7 {
Will this ever be greater than 7?

2020-10-22 07:50 UTC, joshuef requested changes

2020-10-22 07:50 UTC, joshuef commented on src/client/transfer_actor/balance_management.rs
>          let res = client.send_money(wallet1, Money::from_str("5000")?).await;
This should still be another test @Yoga07

2020-10-22 07:50 UTC, joshuef commented on src/client/transfer_actor/mod.rs
> +                "Unexpected response when retrieving account history {:?}",
```suggestion
                "Unexpected response when retrieving store core {:?}",
```

2020-10-22 07:50 UTC, joshuef commented on src/connection_manager.rs
> +            if self.elders.len() >= 7 {
Should be ideal... but what if we're not in ideal conditions? for a client what is _enough_? 3 elders? 5? 7?

If we cannot get 7, i'd say 5 should be sufficient for most ops. The elders will comm between themselves no?

Or are we saying if we cannot connect to 7, there's an issue worth failing over?

2020-10-22 07:50 UTC, joshuef commented on src/utils/mod.rs
> +    Cmd::Data { cmd, payment }
IMO this util wrapper func doesn't add thaaat  much. We loose more in terms of `use::util::wrap_data_cmd` than just having this implemented at each point...

We loose clarity, and it's the same (or more) LOC, i think.

2020-10-22 07:55 UTC, Yoga07 commented on src/connection_manager.rs
> +            if self.elders.len() >= 7 {
In the future maybe? When we move away from static `ELDER_SIZE` in routing. But yea, it's a long way ahead.

2020-10-22 08:19 UTC, joshuef commented on src/connection_manager.rs
> +            if self.elders.len() >= 7 {
If we ever have flexi elder numbers, could be. 

I guess the arg for 7 is that anything less and we cannot trust elders... You could have 2 under DOS by 3 elders, and then they have majority over what happens... Still, impact would only be about GETs, (with any pay ops needing sig) but could be a pain.

So aye, actually 7 is good I guess :+1:

2020-10-22 09:04 UTC, joshuef approved these changes

2020-10-22 09:07 UTC, merged