Recursively delete all blobs
maidsafe/sn_client pull request #1377
Opened 2021-02-15 06:37 UTC by kanav99

Fixes https://github.com/maidsafe/self_encryption/issues/252

Deletes all the blobs until the root blob is found. Previously only the outermost blob was deleted.

2021-02-15 07:06 UTC, lionel1704 requested changes
Hi @kanav99 I think you are missing some parts of this. Let me try to elaborate what is happening.

1. Given a blob address, we first fetch the raw data.
2. This raw data is definitely a data map.
3. Once this raw data is fetched, this blob has to be deleted.
4. Deserialize the raw data into `DataMap`.
5. 
  ### Case 1:
  - `DataMap::Child`
  -  Read raw data using `read_using_data_map`
  - We need to add a `delete_using_data_map` function that will use the data map and delete all the chunks listed in the map.
  - This raw data is again definitely a `DataMap`
  - Repeat from step 3
  
  ### Case 2:
  - `DataMap::Root`
  - This means that after calling `read_using_data_map` we would get the raw data that was sent by the user.
  - We don't need to fetch the raw data, so we can just call `delete_using_data_map` and delete all the chunks from the network.
  
 Please let me know if you have any questions

2021-02-19 12:44 UTC, lionel1704 commented on src/client/blob_storage.rs
> +            // Should raise error though
This comment is right. An error can be returned here.

2021-02-23 06:40 UTC, kanav99 commented on src/client/blob_storage.rs
> +            // Should raise error though
Done!

2021-02-23 06:53 UTC, lionel1704 submitted a review, later dismissed
Great work! :tada:

2021-02-23 07:17 UTC, lionel1704 approved these changes

2021-02-23 07:17 UTC, merged