Update to the latest qp2p API
maidsafe/sn_client pull request #1378
Opened 2021-02-15 08:38 UTC by lionel1704

2021-02-15 10:58 UTC, joshuef approved these changes

2021-02-15 12:52 UTC, bochaco commented on src/connection_manager.rs
> +type ElderConnectionMap = BTreeSet<SocketAddr>;
Not a big deal I think, but since we are using `HashSet` in this and other crates for the bootstrapping/hard-coded contacts list, perhaps also use it for this here?

2021-02-15 13:16 UTC, lionel1704 commented on src/connection_manager.rs
> +type ElderConnectionMap = BTreeSet<SocketAddr>;
Sure. I can make that change. I'm going to do a rebase now, will include this change as well.

2021-02-15 13:25 UTC, bochaco commented on src/connection_manager.rs
> +            error!("IncomingMessages listener is closing now");
I don't think this should be an `error` level log but a `warn`? otherwise we wouldn't be returning `Ok(())`

2021-02-15 13:27 UTC, bochaco commented on src/connection_manager.rs
> +                        error!("Could not deserialize MessageEnvelope");
Same comment about `error` level log as below, it doesn't seem an error but just a scenario being handled which we my just wanna warn about with `warn` or simply `info`

2021-02-15 14:29 UTC, bochaco requested changes

2021-02-15 14:29 UTC, bochaco commented on src/connection_manager.rs
> +                    Err(Error::UnexpectedMessageOnJoin(format!("Client should re-bootstrap with a new set of Elders, but it's not yet supported: {:?}",addresses)))
Note this has been fixed/implemented recently, so this probably was missed when rebasing, this was implemented with:
```
 trace!("GetSectionResponse::Redirect, trying with provided elders");
 Ok(addresses)
```

2021-02-16 08:36 UTC, joshuef approved these changes

2021-02-16 08:48 UTC, merged