feat(examples): add a simple example using Blob API
maidsafe/sn_client pull request #1508
Opened 2021-05-18 03:23 UTC by bochaco

2021-05-18 05:23 UTC, joshuef commented
Let's get this example run as part of the test suites so it never goes out of date :+1:

2021-05-18 06:15 UTC, joshuef requested changes
(as above)

2021-05-18 14:05 UTC, bochaco commented
> Let's get this example run as part of the test suites so it never goes out of date +1

Ok, let's wait for your PR to be merged as that's adding the logic to start a network.

2021-05-19 14:02 UTC, S-Coyle approved these changes

2021-05-19 14:04 UTC, merged